### ISSUE TITLE
markers with mixed styles not being interpreted

### ISSUE THREAD

**Issue by kphunter** [BCIT-LTC/dewordify#16]
I'm getting markout errors whenever an opening marker is styled differently from a closing marker (and vice versa). Errors are generated on text that is bolded or italicized, but it may also extend to highlighted text, coloured text and other styles...

To reproduce, run dewordify on this [test.docx](https://github.com/BCIT-LTC/dewordify/files/1142827/test.docx).

**Comment by MCTaylor17** [comment]
There is no problem with the output.  It was just miscounting `<p><strong>#marker</strong></p>` as two rather than 1.

I tightened up the scanning method in 1d3ae4c
