### ISSUE TITLE
weird links

### ISSUE THREAD

**Issue by kphunter** [BCIT-LTC/dewordify#20]
I'm seeing weird links in the converted source of the attached file: [new-test.docx](https://github.com/BCIT-LTC/dewordify/files/1215872/new-test.docx)

This reminds me of an issue we've seen before: https://issues.ltc.bcit.ca/production/dewordify/issues/8 
(apologies for the internal link - here's a screenshot of the history for reference).

![remove-anchor-tags](https://user-images.githubusercontent.com/5122386/29184707-f1b57b6a-7dbb-11e7-8179-645f8da85d19.png)

Can we have Dewodify remove these empty anchor tags?

**Comment by MCTaylor17** [comment]
Converting the file you provided I see this:

```html
<p><a id="_wawy7o22zdd"></a></p>
```

I searched the xml and found this:

```xml
<w:bookmarkStart w:id="0" w:name="_wawy7o22zdd" w:colFirst="0" w:colLast="0" />
<w:bookmarkEnd w:id="0" />
```

Which means this is the culprit:

![image](https://user-images.githubusercontent.com/7216377/31693596-5826379a-b354-11e7-8c3e-c3bd1b36144c.png)

**Comment by MCTaylor17** [comment]
Simple solution:  I'm removing any anchor tags that don't have an `href` attribute.
