### ISSUE TITLE
feature request: no convert/comment out marker

### ISSUE THREAD

**Issue by kphunter** [BCIT-LTC/dewordify#21]
When I see some kinds of content - like self-assessment questions - embedded directly in the Word blueprint, it's hard to find it/work with it after it's been converted (eg. if it's being re-factored into an [on-page multiple choice interactivity](https://learn.bcit.ca/d2l/le/content/29311/viewContent/1240712/View)):

![on-page-multiple-choice](https://user-images.githubusercontent.com/5122386/29893325-8fbaa784-8d86-11e7-9df5-97145aebdd22.PNG)

If this content is removed in the Word doc, I've got to toggle between 2 sources to rebuild it.

I would find it useful to be able to have entire sections of a Word document commented out automatically. Perhaps a marker like `#comment` or `#no-convert` might work. I don't think it would matter if it gets converted to html or if it stays in some kind of text form.

**Comment by MCTaylor17** [comment]
Assuming you want the contents of the marker to be moved into an HTML comment (eg `<!-- In here -->`) , then I'm not sure I like `#no-convert` as it implies that the text would still be visible.  Conversely, `#comment` seems appropriate, but I would be worried about an uninformed content developer accidentally inventing as some kind of speech bubble or something.  I think we've seen `#instruction` used which is not far off...

Perhaps `#hidden`, `#ignore`, `#html-comment`, or even something more abstract like `#*`

**Comment by kphunter** [comment]
I prefer #html-comment most out of the options you suggested...

**Comment by MCTaylor17** [comment]
09e42f0 implements this feature using #html-comment as requested
