### ISSUE TITLE
#reveals not converted when nested within learning blocks

### ISSUE THREAD

**Issue by kphunter** [BCIT-LTC/dewordify#22]
I noticed #reveals are not getting converted when they're nested within other learning blocks. With the following Test document, the reveal marker text is converted into <p> tags.

[Test.docx](https://github.com/BCIT-LTC/dewordify/files/1361029/Test.docx)

Is this a result of a recent change to Cheerio? Can this be fixed please?

**Comment by MCTaylor17** [comment]
This was accidentally introduced in fix to #16.  I was trying to avoid bold and italic tags from triggering a miscount by targeting only elements in at the root level.  Unfortunately, elements don't stay at the root once they're wrapped...

Anyways, consider it fixed.
