### ISSUE TITLE
No warning regarding unrecognized marker

### ISSUE THREAD

**Issue by MCTaylor17** [BCIT-LTC/dewordify#41]
A document seemed to pass by two people with a `#key point` marker (notice the space rather than hyphen) without drawing any attention.

**Comment by MCTaylor17** [comment]
I thought this was a problem with Dewordify but I couldn't replicate it.  We couldn't replicate it on one of the original reviewer's computer either.  It's probably safe to assume the warning was there but went unnoticed.

@kphunter do you think the warning message need to be more prominent or is it more of a training issue?

**Comment by kphunter** [comment]
Unrecognized markers now display prominently with c7eab3404a9957487646d454ae6ddc89e1b835b7.
