### ISSUE TITLE
Self-test enhancement

### ISSUE THREAD

**Issue by kphunter** [BCIT-LTC/dewordify#44]
**We like on-page question/answer mechanisms!** This replaces the [D2L CoP Multiple Choice self-test](https://learn.bcit.ca/d2l/le/content/29311/viewContent/1240712/View).

Here's what the group decided:
* marker will be #self-test
* start with 2 question types:
  * Multiple Choice (which includes True/False)
  * Multiple Select
  * neither of these question types require a "type"
* feedback is initiated with the @ symbol
* feedback can be general question feedback, or option-specific feedback, or both
* questions are formatted using Word lists:
  * an ordered list retains the question order
  * an unordered list (bullet list) randomizes the order
  * randomization can be at the question level, the option level, or both

**Related issue:** [Self-Test Partial](https://issues.ltc.bcit.ca/web-apps/conversion-guide/merge_requests)/24#note_3052

**Comment by MCTaylor17** [comment]
Most of this is unrelated to Dewordify.  The only thing that needs to be done is to update the markoutMap with the self-test marker.
