### ISSUE TITLE
mailto links prefixed with "assets/"

### ISSUE THREAD

**Issue by kphunter** [BCIT-LTC/dewordify#46]
It appears that all "mailto:" links have "assets/" prepended to the beginning of the href.

The following courses have the string "assets/mailto:":

![stash its bcit ca-search-itsstash](https://user-images.githubusercontent.com/5122386/36572306-d10efa70-17ef-11e8-9fd3-51fd6a1de018.jpeg)

@feliciahou are you able to correct the hrefs on the affected pages?

**Comment by MCTaylor17** [comment]
@kphunter I'm adding a couple lines of JS to Sugar in order to deal with any broken URLS out in the wild.
