### ISSUE TITLE
Updating media / interaction source specification

### ISSUE THREAD

**Issue by kphunter** [BCIT-LTC/dewordify#57]
In preparation for #31, #27, and #56, we are moving from the word "File" to the word "Source" as the prefix for media and interaction elements.

This allows content developers to specify a web resource as well as a local asset.

**Comment by arolos** [comment]
@kphunter I noticed that for video we used `Reference:` and for audio its `License:` in the word document for specifying the file license.

**Comment by kphunter** [comment]
@Arv91 good observation...

I'd like to propose that we remove both `Reference:` and `License:` parameters from all markers, and replace the syntax with `#reference` to make things consistent across the board.

`#reference` could always be converted into

```
<footer>
  <small>Reference, license info or whatever...</small>
</footer>
```

And then styled appropriately based on whether it's in a `<figure>`, a `<blockquote>`, or a regular `<p>`.

**Comment by MCTaylor17** [comment]
Yes, then `Source:` and `Alt:` should also be updated to `#source` and `#alt` and everything will finally be consistent.  Then, hashtags will be the only structural tool left to consider.  Think how easy it will be to do things from now on...

Want to allow developers to request specific image options?  Use hashtags:

```txt
#image
#source
moar-hashtags.jpg
/source
#size
half
/size
#position
left
/position
#license
Dedicated to Hashtags
/license
Moar Hashtags!
/image
```

So much simpler than how we would have done things in the past...

```txt
#image
Source: moar-hashtags.jpg
Size: half
Position: left
License: Dedicated to Hashtags
Moar Hashtags!
/image
```

**Comment by MCTaylor17** [comment]
FYI, the example for Video actually says `Reference: License: ...`.  It's a typo.
