### ISSUE TITLE
Sugar.js features inside a list wasn't converted

### ISSUE THREAD

**Issue by arolos** [BCIT-LTC/dewordify#63]
Text inside a list that doesn't end with `<br>` won't be wrapped with a `<p>`. If the end of a feature (eg:`/image`) is at the end of a list, this won't get processed and dewordify can't find where the feature ends.

**Comment by MCTaylor17** [comment]
I'm curious about this issue.  No closing reason provided.  The paragraph wrapper activates automatically in the presence of a `<br>` tag.  The last paragraph should always be wrapped because it treats the break tag as a splitting point for an array or HTML, is I remember correctly..

**Comment by arolos** [comment]
@MCTaylor17 The problem was if the `/feature` is at the of a list which means it end with a hard return, that text would not be wrapped with a `<p>` because there is no `<br>` at the end of the list and dewordify can't find the closing of that particular feature.
