### ISSUE TITLE
Error renaming image files when alternate assets are specified

### ISSUE THREAD

**Issue by kphunter** [BCIT-LTC/dewordify#8]
When I run Dewordify's *estimate* command, any images embedded in the document are extracted, named and saved to the *assets/* folder. This is expected behaviour and inconsequential except when the *File:...* marker attribute is used to specify an alternate image located in the *assets/* folder (as outlined in the [conversion guide](https://ltc.bcit.ca/courseproduction/conversionguide/pages/marker-quick-reference.html)).

![image-file-issue](https://user-images.githubusercontent.com/5122386/27150934-d9c9f1ce-50fd-11e7-98e7-f8e234b81115.PNG)

When *estimate* is run using a document that references images in the *assets/* folder, I'm seeing **"Error renaming file"**.

![dewordify-image-error](https://user-images.githubusercontent.com/5122386/27150481-484728b2-50fc-11e7-815c-6d583d1ddd21.PNG)

**Other observations**
* this error exists regardless if there are actually any image files in the *assets/* folder
* despite the error, images embedded in the document are extracted, numbered and saved in the *assets/* folder

**Comment by MCTaylor17** [comment]
The `File:` interface is really just for naming purposes.  It's assumed that whatever hi-resolution images are provided will be manually placed into our assets folder in production.

## Solution: 

Instead of `File: assets/filename.jpg` use `File: filename.jpg`
