### ISSUE TITLE
Find a solution for old commit messages referencing GitLab issues

### ISSUE THREAD

**Issue by kphunter** [BCIT-LTC/dewordify#9]
After migrating from our in-house GitLab platform to GitHub, we've realized commit messages referring to GitLab issues will begin to overlap with new GitHub issues.

> eg. aba3af62882fc71ad3b8bc75071826b57aef0e19 refers to `issue #9` in GitLab

**Two potential options:**
1. removing/replacing references to specific issues in the commit history using `git commit --amend`
   - **Con:** we lose a hyperlink and unless the *Issue Title* is added to the message, we lose the context of what was addressed
   - **Con:** issues in GitLab are not recorded in GitHub
   - See https://help.github.com/articles/changing-a-commit-message/
1. migrating all open/closed GitLab issues to GitHub
   - **Con:** issues will be numbered differently
   - **Con:** old commit messages need to be amended

Are there other options available? Which option is the lesser of the two evils?

**Comment by MCTaylor17** [comment]
At this point, lets just leave it.  They don't seem to create references in the GitHub issues themselves which was my primary concern.  They will only cause confusion to people looking at old commits - People who are probably savvy enough to look past the comments and read the code to figure out why the change was made.
