### ISSUE TITLE
Add knowing and doing learning block

### ISSUE THREAD

**Issue by arolos** [BCIT-LTC/dewordify#97]
Add knowing and doing learning block to the `markoutMap.json`

**Comment by kphunter** [comment]
Includes the following icons:

### Doing
![doing](https://github.com/user-attachments/assets/daa16409-fd61-4182-b1b7-3799fd3e824d)

### Knowing
![knowing](https://github.com/user-attachments/assets/20ff0cc0-ca02-49e7-90d5-f8ca0a31a757)
